<?php

namespace AppBundle\Repository;

/**
 * ArchiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAddressStatus(): array
    {

        return $this->createQueryBuilder('addressArchive')
            ->select('addressArchive.id', 'address.name')
            ->join('addressArchive.objectType', 'address')
            ->where('address.status = :status')
            ->setParameter('status', 0)
            ->getQuery()
            ->execute();
    }

}
