<?php

namespace AppBundle\Repository;

/**
 * CarAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarAdminRepository extends \Doctrine\ORM\EntityRepository
{
}
