<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends EntityRepository
{
    public function findFreeOrder()
    {
        return $this->createQueryBuilder('orders')
            ->select('orders.status', 'orders.id', 'orders.fromAddress', 'orders.toAddress')
            ->where('orders.status = :status')
            ->setParameter('status', 'call')
            ->orderBy('orders.id', 'ASC')
            ->getQuery()
            ->execute();
    }

    public function findDriverOrders()
    {

        return $this->createQueryBuilder('orders')
            ->select('orders.status', 'car.carName', 'orders.id', 'orders.fromAddress', 'orders.toAddress')
            ->join('orders.userOrder', 'user')
            ->join('orders.car', 'car')
            ->orderBy('orders.id', 'ASC')
            ->getQuery()
            ->execute();
    }
}
