services:
#    app.admin.car_admin:
#        class: AppBundle\Admin\CarAdminAdmin
#        arguments: [~, AppBundle\Entity\CarAdmin, Sonata\AdminBundle\Controller\CRUDController]
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: admin, label: CarAdmin }
#        public: true

    app.admin.orders:
        class: AppBundle\Admin\OrdersAdmin
        arguments: [~, AppBundle\Entity\Orders, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Orders }
        public: true
